#logging:
#  level:
#    org.springframework: DEBUG
server: 
  port: 8443  # Specify the port for HTTPS
  address: 0.0.0.0  
  servlet:
    context-path: /portfolio
    encoding:
      charset: UTF-8
#  ssl:    
#    key-store: classpath:keys/keystore_portfolio.pfx # Replace with the actual path
#    key-store-password: 888888 # Use single quotes for password with special characters
#    key-store-type: PKCS12
#    enabled: true  # Enable SSL

# OpenSSL + Certificate  
server.ssl.enabled: true
server.ssl.key-store: classpath:keys/keystore_portfolio.pfx
server.ssl.key-store-password: 888888
server.ssl.key-store-type: PKCS12
     
  
spring:
  thymeleaf:
    cache:  false
    mode: HTML
    encoding: UTF-8
  datasource:    
    url: jdbc:mysql://localhost:3306/portfolio_security?serverTimezone=GMT%2B8&characterEncoding=utf-8&useUnicode=true 
    username: User1
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL  
    show-sql: false  
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true